//! Known answers pinned from `spec` (generated by `bench/src/bin/kat.rs`, which checks
//! them against the dispatched backend), the SMHasher verification values, and
//! structural properties. Input byte `i` is `(i * 31 + 7) as u8`.
use lanehash::{hash128, hash64};

fn buf(n: usize) -> Vec<u8> {
    (0..n).map(|i| (i * 31 + 7) as u8).collect()
}

#[test]
fn known_answers_match_the_prototype() {
    const KAT: &[(usize, u64, u64)] = &[
    (65, 0x0, 0x2346681288f51157),
    (65, 0x1, 0x8b0b17d055600fa3),
    (65, 0x9e3779b97f4a7c15, 0x2e59c0974799e010),
    (65, 0xffffffffffffffff, 0xe28a3fc092035c59),
    (66, 0x0, 0x88e17a243c049b6e),
    (66, 0x1, 0x287c45cd4166d180),
    (66, 0x9e3779b97f4a7c15, 0x953345e303f023f2),
    (66, 0xffffffffffffffff, 0x8a15ae22ae0d9bbf),
    (96, 0x0, 0xdbaa35ca1a996ebe),
    (96, 0x1, 0x8030ec1a18480b35),
    (96, 0x9e3779b97f4a7c15, 0x79bdab62e4bdf4db),
    (96, 0xffffffffffffffff, 0x98dd8d555dd482a5),
    (127, 0x0, 0x4b4ce8f994ee10f3),
    (127, 0x1, 0x6fec6a6b8c91007b),
    (127, 0x9e3779b97f4a7c15, 0x77835e6c930ae709),
    (127, 0xffffffffffffffff, 0x50004bee9187ac00),
    (128, 0x0, 0x4b89a72530cf9ac7),
    (128, 0x1, 0x3c59dc18c8a10a83),
    (128, 0x9e3779b97f4a7c15, 0x44e824ca1bdf9aed),
    (128, 0xffffffffffffffff, 0x60a287eb85cb9631),
    (129, 0x0, 0xcc23a647f6696700),
    (129, 0x1, 0xcc09f5bd481d7cd0),
    (129, 0x9e3779b97f4a7c15, 0xeb36a55da6a9cde6),
    (129, 0xffffffffffffffff, 0x8fe9c7f4d039fea5),
    (191, 0x0, 0x377e4a44bb3fbc0a),
    (191, 0x1, 0x3da0d882438f8955),
    (191, 0x9e3779b97f4a7c15, 0xa9aa3af3da720e95),
    (191, 0xffffffffffffffff, 0xa3595e5c0371c336),
    (192, 0x0, 0x128cb194b26b2943),
    (192, 0x1, 0x9b44d297072bf89e),
    (192, 0x9e3779b97f4a7c15, 0x3871a6e46c27b38e),
    (192, 0xffffffffffffffff, 0x007ad8e9a752665f),
    (255, 0x0, 0xf5458be6ad8df28c),
    (255, 0x1, 0x11f59b351224c5d9),
    (255, 0x9e3779b97f4a7c15, 0x9f3fc5282d562619),
    (255, 0xffffffffffffffff, 0xe43b2fd93a7605b4),
    (256, 0x0, 0xe6a2a843eefc3073),
    (256, 0x1, 0x179a2e2ef535f01d),
    (256, 0x9e3779b97f4a7c15, 0xc4aecf66af5930b9),
    (256, 0xffffffffffffffff, 0x5db33847e028108e),
    (257, 0x0, 0x3d1e15fb0332e1ef),
    (257, 0x1, 0xf90f3331a63937f9),
    (257, 0x9e3779b97f4a7c15, 0xde585d7cbf4818be),
    (257, 0xffffffffffffffff, 0x14651151a9fffcec),
    (511, 0x0, 0x911fe43f226a6fdb),
    (511, 0x1, 0x57ed858a2227ab47),
    (511, 0x9e3779b97f4a7c15, 0x886df41ad48b363d),
    (511, 0xffffffffffffffff, 0x1613025111cc6e03),
    (512, 0x0, 0x2c3158ed8e436ed0),
    (512, 0x1, 0x40f8cc27144cc3da),
    (512, 0x9e3779b97f4a7c15, 0xfb8ba4837d88b9f3),
    (512, 0xffffffffffffffff, 0xd858f0bba7c629ca),
    (1023, 0x0, 0x016ac15bc677235a),
    (1023, 0x1, 0x835ba91aca4ef5d2),
    (1023, 0x9e3779b97f4a7c15, 0x9b5bd0c29e7745aa),
    (1023, 0xffffffffffffffff, 0x3b1159b611204d67),
    (1024, 0x0, 0x161db0018a3ca65e),
    (1024, 0x1, 0x2adb4ba680b5c69d),
    (1024, 0x9e3779b97f4a7c15, 0x563c656656486899),
    (1024, 0xffffffffffffffff, 0x41c4bdee0e7164ba),
    (1025, 0x0, 0x02573186e7f9c1f9),
    (1025, 0x1, 0xcb16974e40491c24),
    (1025, 0x9e3779b97f4a7c15, 0xa3f069fa585d4bd9),
    (1025, 0xffffffffffffffff, 0x881846df38d997b6),
    (4096, 0x0, 0x0ef1566471f573cb),
    (4096, 0x1, 0x586b484a8ffaba21),
    (4096, 0x9e3779b97f4a7c15, 0xf905bd0b86cc41a6),
    (4096, 0xffffffffffffffff, 0xbe3b1edc92470eef),
    (8191, 0x0, 0x09cd7b1b869a7eba),
    (8191, 0x1, 0x4c79a6183e5a48fa),
    (8191, 0x9e3779b97f4a7c15, 0xeaf3c3cdfa5d6beb),
    (8191, 0xffffffffffffffff, 0xa3489ceb64b80a5b),
    (8192, 0x0, 0xdec508db1abdb425),
    (8192, 0x1, 0xe5eaca28a3132cd5),
    (8192, 0x9e3779b97f4a7c15, 0xdd0734894cefb2dc),
    (8192, 0xffffffffffffffff, 0xecf89bd4b12717f9),
    (8193, 0x0, 0x40dcce7f8a0b9cec),
    (8193, 0x1, 0xe8f07325dbd3a45c),
    (8193, 0x9e3779b97f4a7c15, 0x6a3f952ac1c943b2),
    (8193, 0xffffffffffffffff, 0x4818af14cbb148e5),
    (65535, 0x0, 0x06389c271dacfa15),
    (65535, 0x1, 0x8ef756a9e570badc),
    (65535, 0x9e3779b97f4a7c15, 0x2b74b4a667b43532),
    (65535, 0xffffffffffffffff, 0xc4b5bf1687e38a73),
    (65536, 0x0, 0xc21ce9a4e74e818c),
    (65536, 0x1, 0x7cb3577c18446472),
    (65536, 0x9e3779b97f4a7c15, 0x2e28e29d7968b22e),
    (65536, 0xffffffffffffffff, 0xed923239ab88075e),
    (65537, 0x0, 0x903196c979b203a7),
    (65537, 0x1, 0x1ae896405d91acc4),
    (65537, 0x9e3779b97f4a7c15, 0x09110e46df1275e3),
    (65537, 0xffffffffffffffff, 0xc0a32991f93c8453),
    (1048569, 0x0, 0xd92a90ae9357192e),
    (1048569, 0x1, 0xa03da32304f8d121),
    (1048569, 0x9e3779b97f4a7c15, 0x42ebd30d1d253225),
    (1048569, 0xffffffffffffffff, 0xa8546467dce30a46),
    (1048576, 0x0, 0xc2bb6643df88c25c),
    (1048576, 0x1, 0x0714e19d6aa5cada),
    (1048576, 0x9e3779b97f4a7c15, 0x7735f9fdaa5b2963),
    (1048576, 0xffffffffffffffff, 0xf07a011af4852c8c),
    (1048583, 0x0, 0x92e94913a36920da),
    (1048583, 0x1, 0xceb890d437e8070f),
    (1048583, 0x9e3779b97f4a7c15, 0x0c143c071daf84c4),
    (1048583, 0xffffffffffffffff, 0x78fa7d669b44422d),
    ];
    let b = buf(if cfg!(miri) { 65537 } else { (1 << 20) + 7 });
    for &(n, seed, want) in KAT {
        if cfg!(miri) && n > 65537 {
            continue; // the megabyte answers take hours under Miri; the backends are the same code
        }
        assert_eq!(hash64(&b[..n], seed), want, "n={n} seed={seed:#x}");
        assert_eq!(hash128(&b[..n], seed) as u64, want, "hash128 low half, n={n} seed={seed:#x}");
    }
}

/// SMHasher's verification value: low 32 bits of the hash of the concatenated hashes of
/// `key[..i]` (`key[i] = i`) under seed `256 - i`.
#[test]
fn smhasher_verification_values() {
    let mut key = [0u8; 256];
    let mut h64 = [0u8; 8 * 256];
    let mut h128 = [0u8; 16 * 256];
    for i in 0..256 {
        key[i] = i as u8;
        let seed = 256 - i as u64;
        h64[8 * i..8 * i + 8].copy_from_slice(&hash64(&key[..i], seed).to_le_bytes());
        h128[16 * i..16 * i + 16].copy_from_slice(&hash128(&key[..i], seed).to_le_bytes());
    }
    assert_eq!(hash64(&h64, 0) as u32, 0xd048_c22b, "lanehash64 verification value");
    assert_eq!(hash128(&h128, 0) as u32, 0xc2f3_9939, "lanehash128 verification value");
}

/// At every length the 128-bit output's low half is the 64-bit output, its high half
/// differs, and seed and length matter.
#[test]
fn structure() {
    let b = buf(1100);
    for n in 0..=64 {
        assert_eq!(hash128(&b[..n], 7), lanehash::short::short128(&b[..n], 7), "short path n={n}");
        assert_eq!(hash64(&b[..n], 7), lanehash::short::short64(&b[..n], 7), "short path n={n}");
    }
    for n in 1..=1100 {
        let (h, w) = (hash128(&b[..n], 7), hash64(&b[..n], 7));
        assert_eq!(h as u64, w, "n={n}");
        assert_ne!((h >> 64) as u64, w, "n={n}");
        assert_ne!(hash64(&b[..n], 7), hash64(&b[..n], 8), "seed n={n}");
        assert_ne!(hash64(&b[..n], 7), hash64(&b[..n - 1], 7), "length n={n}");
    }
}
