#!/usr/bin/env python3
"""Regenerate lanehash_aes_ttables.h (AES T-tables) from the S-box in lanehash_aes_constants.h."""
import re
src = open("lanehash_aes_constants.h").read()
m = re.search(r"LH_SBOX\[256\] = \{(.*?)\};", src, re.S)
sbox = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]{2}", m.group(1))]
assert len(sbox) == 256
xt = lambda a: ((a << 1) ^ (((a >> 7) & 1) * 0x1b)) & 0xff
mul = lambda m, s: s if m == 1 else xt(s) if m == 2 else xt(s) ^ s
rows = [(2, 1, 1, 3), (3, 2, 1, 1), (1, 3, 2, 1), (1, 1, 3, 2)]
out = ["/* Generated by gen_ttables.py from the AES S-box: LH_TE[r][v] is the MixColumns",
       " * contribution of S[v] at row r, packed little-endian (same tables as",
       " * lanehash/src/soft.rs). Used by the portable (software AES) build only. */",
       "static const uint32_t LH_TE[4][256] = {"]
for r in range(4):
    out.append("    {")
    vals = []
    for s in sbox:
        b = [mul(rows[r][i], s) for i in range(4)]
        vals.append("0x%08x" % (b[0] | b[1] << 8 | b[2] << 16 | b[3] << 24))
    for i in range(0, 256, 8):
        out.append("        " + ", ".join(vals[i:i + 8]) + ",")
    out.append("    },")
out.append("};")
open("lanehash_aes_ttables.h", "w").write("\n".join(out) + "\n")
